apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: my-postgresql-operator-dev4devs-com
  name: api-accessor
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps"]
  verbs: ["get", "watch", "list", "create"]
